# Generated by Django 5.2.4 on 2025-07-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickedcoordinate',
            name='comments',
            field=models.TextField(default='', help_text='Please only add additional comments if necessary.'),
        ),
        migrations.AddField(
            model_name='rating',
            name='comments',
            field=models.TextField(default='', help_text='Please only add additional comments if necessary.'),
        ),
        migrations.AlterField(
            model_name='clickedcoordinate',
            name='source_data_issue',
            field=models.BooleanField(default=False, verbose_name='I suspect there might be a problem with the image quality'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='source_data_issue',
            field=models.BooleanField(default=False, verbose_name='I suspect there might be a problem with the image quality'),
        ),
    ]
