[project]
name = "django-dirt-ratings"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Patrick Sadil", email = "psadil@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "celery>=5.6.0",
    "django>=6.0.0",
    "django-typer>=3.2.0",
    "django-ninja>=1.2.0",
    "orjson>=3.11.1",
    "neurorm @ git+https://github.com/psadil/neurorm.git",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[dependency-groups]
dev = ["celery-types>=0.23.0", "django-stubs>=5.2.2", "jupyter>=1.1.1"]
manage = [
    "dipy>=1.11.0",
    "imageio>=2.37.0",
    "matplotlib>=3.10.3",
    "neurorm",
    "nibabel>=5.3.2",
    "nilearn>=0.12.0",
    "nitransforms>=25.0.0",
    "numpy>=2.3.1",
    "polars>=1.31.0",
    "pygifsicle>=1.1.0",
]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
django-dirt-ratings = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }
manage = { features = ["manage"], solve-group = "default" }

[tool.pixi.tasks]
